siteweather/siteweather/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from siteweather import settings
from weather.views import PageNotFound404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls')),
    path('users/', include('users.urls', namespace="users")),

]

handler404 = PageNotFound404.as_view()

admin.site.site_header = 'Панель администрирования проекта "Погода"'
admin.site.index_title = 'Проект "Погода"'

siteweather/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path(route='login/', view=views.LoginUser.as_view(), name='login'),
    path(route='logout/', view=LogoutView.as_view(), name='logout'),
    path(route='register/', view=views.RegisterUser.as_view(), name='register'),
    path(route='profile/', view=views.ProfileUser.as_view(), name='profile'),
    path(route='password-change/', view=views.UserPasswordChange.as_view(), name='password_change'),
    path(route='password-change/done/',
         view=PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'
    ),
    path(route='password-reset/',
         view=PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                        email_template_name='users/password_reset_email.html',
                                        success_url=reverse_lazy('users:password_reset_done')
                                        ),
         name='password_reset'
         ),
    path(route='password-reset/done/',
         view=PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'
         ),
    path(route='password-reset/<uidb64>/<token>/',
         view=PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                                success_url=reverse_lazy('users:password_reset_complete')
                                               ),
         name='password_reset_confirm'
         ),
    path(route='password-reset/complete/',
         view=PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'
         ),
]

siteweather/users/models.py
from django.db import models

# Create your models here.

siteweather/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин')
    password = forms.CharField(label='Пароль')

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин')
    password1 = forms.CharField(label='Пароль')
    password2 = forms.CharField(label='Повтор пароля')

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2']
        labels = {'email': 'E-mail'}


    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError('Пользователь с таким E-mail уже существует')
        return email


class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(disabled=True, label='Логин')
    email = forms.CharField(disabled=True, label='E-mail')

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия'}


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label='Старый пароль')
    new_password1 = forms.CharField(label='Новый пароль')
    new_password2 = forms.CharField(label='Подтверждение пароля')

siteweather/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from .forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm


class LoginUser(LoginView):
    from_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Авторизация'}


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Регистрация'}
    success_url = reverse_lazy('users:login')


class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'Профиль пользователя'}

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"

siteweather/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<br>
<main style="width: 500px; margin: 0 auto;">
  <h1 class="h3 mb-3 fw-normal" style="text-align: center;">{{ title }}</h1>

  <form method="post">
    {% csrf_token %}
    <div class="text-danger">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label style="display: inline-block; min-width: 150px; vertical-align: top;" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="text-danger">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit" class="btn btn-outline-success w-100 py-2">Войти</button></p>

    <p><a href="#">Забыли пароль?</a></p>
  </form>

</main>

{% endblock %}

siteweather/users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% block content %}
<br>
<h1 class="h3 mb-3 fw-normal" style="text-align: center;">Пароль успешно изменен!</h1>
<p>Вы успешно изменили пароль!</p>
<p><a href="{% url 'users:profile' %}">Венруться в профиль</a></p>

{% endblock %}

siteweather/users/templates/users/password_change_form.html
{% extends 'base.html' %}

{% block content %}
<br>
<main style="width: 500px; margin: 0 auto;">
  <h1 class="h3 mb-3 fw-normal" style="text-align: center;">{{ title }}</h1>

  <form method="post">
    {% csrf_token %}
    <div class="text-danger">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label style="display: inline-block; min-width: 150px; vertical-align: top;" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="text-danger">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit" class="btn btn-outline-success w-100 py-2">Изменить пароль</button></p>
  </form>

</main>

{% endblock %}

siteweather/users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<br>
<main style="width: 500px; margin: 0 auto;">
  <h1 class="h3 mb-3 fw-normal" style="text-align: center;">{{ title }}</h1>

  <p>Поздравляем! Вы успешно поменяли пароль своего аккаунта!</p>
  <p>Используйте его для <a href="{% url 'users:login' %}">входа в систему</a></p>

</main>

{% endblock %}

siteweather/users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<br>
<main style="width: 500px; margin: 0 auto;">
  <h1 class="h3 mb-3 fw-normal" style="text-align: center;">{{ title }}</h1>

  <form method="post">
    {% csrf_token %}
    <div class="text-danger">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label style="display: inline-block; min-width: 150px; vertical-align: top;" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="text-danger">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit" class="btn btn-outline-success w-100 py-2">Сохранить</button></p>
  </form>

</main>

{% endblock %}

siteweather/users/templates/users/password_reset_done.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<br>
<main style="width: 500px; margin: 0 auto;">
  <h1 class="h3 mb-3 fw-normal" style="text-align: center;">{{ title }}</h1>

  <p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

  <p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

</main>

{% endblock %}

siteweather/users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

siteweather/users/templates/users/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
<br>
<main style="width: 500px; margin: 0 auto;">
  <h1 class="h3 mb-3 fw-normal" style="text-align: center;">{{ title }}</h1>

  <form method="post">
    {% csrf_token %}
    <div class="text-danger">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label style="display: inline-block; min-width: 150px; vertical-align: top;" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="text-danger">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit" class="btn btn-outline-success w-100 py-2">Сбросить пароль по E-mail</button></p>
  </form>

</main>

{% endblock %}

siteweather/users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<br>
<main style="width: 500px; margin: 0 auto;">
  <h1 class="h3 mb-3 fw-normal" style="text-align: center;">{{ title }}</h1>

  <form method="post">
    {% csrf_token %}
    <div class="text-danger">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label style="display: inline-block; min-width: 150px; vertical-align: top;" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="text-danger">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit" class="btn btn-outline-success w-100 py-2">Сохранить</button></p>
  </form>

</main>

{% endblock %}

siteweather/users/templates/users/register.html
{% extends 'base.html' %}

{% block content %}
<br>
<main style="width: 500px; margin: 0 auto;">
  <h1 class="h3 mb-3 fw-normal" style="text-align: center;">{{ title }}</h1>

  <form method="post">
    {% csrf_token %}
    <div class="text-danger">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label style="display: inline-block; min-width: 150px; vertical-align: top;" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="text-danger">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit" class="btn btn-outline-success w-100 py-2">Зарегистрироваться</button></p>

  </form>

</main>

{% endblock %}