siteweather/siteweather/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from siteweather import settings
from weather.views import PageNotFound404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls')),
    path('users/', include('users.urls', namespace="users")),

]

handler404 = PageNotFound404.as_view()

admin.site.site_header = 'Панель администрирования проекта "Погода"'
admin.site.index_title = 'Проект "Погода"'

siteweather/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path(route='login/', view=views.LoginUser.as_view(), name='login'),
    path(route='logout/', view=LogoutView.as_view(), name='logout'),
    path(route='register/', view=views.RegisterUser.as_view(), name='register'),
    path(route='profile/', view=views.ProfileUser.as_view(), name='profile'),
    path(route='password-change/', view=views.UserPasswordChange.as_view(), name='password_change'),
    path(route='password-change/done/',
         view=PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'
    ),
    path(route='password-reset/',
         view=PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                        email_template_name='users/password_reset_email.html',
                                        success_url=reverse_lazy('users:password_reset_done')
                                        ),
         name='password_reset'
         ),
    path(route='password-reset/done/',
         view=PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'
         ),
    path(route='password-reset/<uidb64>/<token>/',
         view=PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                                success_url=reverse_lazy('users:password_reset_complete')
                                               ),
         name='password_reset_confirm'
         ),
    path(route='password-reset/complete/',
         view=PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'
         ),
]

siteweather/weather/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(route='', view=views.WeatherHome.as_view(), name='home'),
    path(route='about/', view=views.AboutProject.as_view(), name='about'),
    path(route='search/', view=views.WeatherSearch.as_view(), name='search'),
    path(route='forecast/<int:location_id>/', view=views.WeatherForecast.as_view(), name='forecast'),

]

siteweather/weather/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Locations(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    latitude = models.DecimalField(max_digits=30, decimal_places=20)
    longitude = models.DecimalField(max_digits=30, decimal_places=20)
    user_id = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='locations', null=False, default=None)


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Локации'
        verbose_name_plural = 'Локации'
        ordering = ['name']
        indexes = [
            models.Index(fields=['name'])
        ]
        unique_together = [['name', 'latitude', 'longitude', 'user_id']]

siteweather/weather/forms.py
from django import forms
from weather.models import Locations


class LocationForm(forms.ModelForm):
    class Meta:
        model = Locations
        fields = []

siteweather/weather/views.py
from django.http import HttpResponse, HttpResponseNotFound, Http404
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from weather.api_services.openweathermap_api import Weather_API_Service
from weather.forms import LocationForm
from weather.models import Locations
from weather.api_services.ISO_country_codes import countries
from django.views.generic import ListView, TemplateView
from django.core.cache import cache



class WeatherHome(ListView):
    template_name = 'weather/index.html'
    context_object_name = 'locations'
    extra_context = {}
    extra_context['title'] = 'Главная страница'
    form_class = LocationForm

    def get_queryset(self):
        locations = Locations.objects.filter(user_id=self.request.user.id).order_by('-id')
        api_obj = Weather_API_Service()
        locations_current_weather_dict = {}
        for location in locations:
            cache_key = 'locations_current_weather_' + str(location.id)
            location_current_weather = cache.get(cache_key)
            if location_current_weather:
                locations_current_weather_dict[location.id] = location_current_weather
            else:
                latitude = str(float(location.latitude))
                longitude = str(float(location.longitude))
                location_current_weather = api_obj.find_current_weather_by_coords(latitude, longitude)
                location_current_weather.city.name = location.name
                cache.set(cache_key, location_current_weather, 60*15)
                locations_current_weather_dict[location.id] = location_current_weather

        return locations_current_weather_dict

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            if 'save' in request.POST:
                return self.post_save_handler(request)
            elif 'delete' in request.POST:
                return self.post_delete_handler(request)

    def post_save_handler(self, request):
        name = request.POST.get('name')
        latitude = float(request.POST.get('latitude').replace(',', '.'))
        longitude = float(request.POST.get('longitude').replace(',', '.'))
        user_id = request.user
        try:
            location = Locations.objects.create(name=name,
                                                latitude=latitude,
                                                longitude=longitude,
                                                user_id=user_id
                                                )
            location.save()
            return redirect('home')
        except Exception:
            request.session['error_message'] = f'Произошла ошибка: город “{name}” уже добавлен ранее'
            request.session['name'] = name
            request.session['latitude'] = latitude
            request.session['longitude'] = longitude
            country = request.POST.get('country')
            request.session['country'] = country
            request.session['country_name'] = countries[country]

            return self.save_error(request)

    def post_delete_handler(self, request):
        location_id = request.POST.get('location_id')
        try:
            location = Locations.objects.get(id=location_id)
            cache_key = str(location.id)
            if cache.has_key(cache_key):
                try:
                    cache.delete(cache_key)
                except Exception as e:
                    print(f"Ошибка очистки кеша: {e}")
            if request.user.id == location.user_id.id:
                location.delete()
            return redirect('home')
        except Exception:
            return redirect('home')

    def save_error(self, request):
        context = {}
        context['title'] = 'Ошибка добавления города'
        context['error_message'] = request.session.get('error_message')
        context['name'] = request.session.get('name')
        context['latitude'] = request.session.get('latitude')
        context['longitude'] = request.session.get('longitude')
        context['country'] = request.session.get('country')
        context['country_name'] = request.session.get('country_name')

        return render(request=request, template_name='weather/save_error.html', context=context)


class WeatherSearch(ListView):
    template_name = 'weather/search.html'
    extra_context = {}
    extra_context['title'] = 'Результаты поиска'
    form_class = LocationForm

    def post(self, request, *args, **kwargs):
        form_data = self.request.POST
        city_name = form_data['city_name']
        self.extra_context['city_name'] = city_name

        api_obj = Weather_API_Service()
        search_result = api_obj.find_by_city(cityname=city_name)
        if isinstance(search_result, list):
            self.extra_context['search_result'] = search_result
            self.extra_context['error_result'] = []
        else:
            self.extra_context['error_result'] = search_result

        return render(request=request, template_name='weather/search.html', context=self.extra_context)


class AboutProject(TemplateView):
    extra_context = {}
    extra_context['title'] = 'О проекте'

    def get(self, request, *args, **kwargs):
        return render(request=request, template_name='weather/about.html', context=self.extra_context)


class WeatherForecast(TemplateView):
    extra_context = {}

    def post(self, request, location_id, *args, **kwargs):
        return self.render_page(request, location_id)

    def get(self, request, location_id, *args, **kwargs):
        locations = Locations.objects.filter(user_id=self.request.user.id).order_by('-id')
        lst_locations_id = [location.id for location in locations]
        if location_id not in lst_locations_id:
            raise Http404('Страница не найдена')
        else:
            return self.render_page(request, location_id)

    def render_page(self, request, location_id, *args, **kwargs):
        location = Locations.objects.get(id=location_id)
        self.extra_context['name'] = location.name
        self.extra_context['title'] = f'Прогноз погоды “{location.name}”'

        cache_key = 'locations_forecast_weather_' + str(location_id)
        forecast = cache.get(cache_key)
        if forecast:
            self.extra_context['forecast'] = forecast
            return render(request=request, template_name='weather/forecast.html', context=self.extra_context)
        else:
            latitude = float(str(location.latitude).replace(',', '.'))
            longitude = float(str(location.longitude).replace(',', '.'))
            api_obj = Weather_API_Service()
            forecast = api_obj.find_forecast_by_coords(latitude, longitude)
            self.extra_context['forecast'] = forecast
            cache.set(cache_key, forecast, 60 * 60)
            return render(request=request, template_name='weather/forecast.html', context=self.extra_context)


class PageNotFound404(TemplateView):
    extra_context = {}
    extra_context['title'] = 'Страница не найдена'

    def get(self, request, exception=None, *args, **kwargs):
        self.extra_context['path'] = request.path
        return render(request=request, template_name='404.html', status=404, context=self.extra_context)

siteweather/weather/templates/weather/about.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>
<h2>Проект “Погода”</h2>
<h3><a href="https://zhukovsd.github.io/python-backend-learning-course/Projects/WeatherViewer/">ТЗ проекта</a></h3>

<p>Веб-приложение для просмотра текущей погоды. Пользователь может зарегистрироваться и добавить в коллекцию один или несколько локаций (городов, сёл, других пунктов), после чего главная страница приложения начинает отображать список локаций с их текущей погодой.</p>
<h3>Используемые инструменты</h3>
<p><ul>
  <li><a href="https://www.python.org/">Python</a> - коллекции, ООП</li>
  <li>Backend - <a href="https://www.djangoproject.com/">Django</a></li>
  <li>Базы данных - <a href="https://www.postgresql.org/">Postgres</a>, <a href="https://docs.djangoproject.com/en/5.0/topics/db/">DjangoORM</a></li>
  <li>Frontend - <a href="https://html.com/html5/">HTML</a>/<a href="https://www.w3schools.com/css/">CSS</a>, <a href="https://getbootstrap.com/">Bootstrap</a></li>
</ul></p>

<h3>Мотивация проекта</h3>
<p><ul>
  <li>Реализация многопользовательского приложения</li>
  <li><a href="https://openweathermap.org/api/">Работа с внешним API (openweathermap.org)</a></li>
</ul></p>

<h3>Функционал приложения</h3>

<h4>Работа с пользователями:</h4>
<p><ul>
  <li><a href="{% url 'users:register' %}">Регистрация</a></li>
  <li><a href="{% url 'users:login' %}">Авторизация</a></li>
  <li>Logout</li>
  {% if user.is_authenticated %}
  <li><a href="{% url 'users:password_change' %}">Изменение пароля</a></li>
  {% else %}
  <li>Изменение пароля</li>
  {% endif %}
  <li><a href="{% url 'users:password_reset' %}">Восстановление пароля</a></li>
</ul></p>

<h4>Работа с локациями:</h4>
<p><ul>
  <li>Поиск</li>
  <li>Добавление в список</li>
  <li>Просмотр списка локаций, для каждой локации отображается название и температура</li>
  <li>Удаление из списка</li>
</ul></p>

{% endblock %}

siteweather/weather/templates/weather/forecast.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}

<h1 class="h1 mb-3 fw-normal" style="text-align: center;">{{ title }} на 5 дней</h1>

<div class="container">
  <div class="row">
    <div class="col-2 d-flex align-items-center justify-content-center">
      <span style="color: gray;">Дата и время</span>
    </div>
    <div class="col-1 d-flex align-items-center justify-content-center">
      <span style="color: gray;">Температура</span>
    </div>
    <div class="col-1 d-flex align-items-center justify-content-center">
      <span style="color: gray;">Ощущается</span>
    </div>
    <div class="col-1 d-flex align-items-center justify-content-center">
    </div>
    <div class="col-2 d-flex align-items-center justify-content-center">
    </div>
    <div class="col-1 d-flex align-items-center justify-content-center">
      <span style="color: gray;">Давление, мм рт.ст.</span>
    </div>
    <div class="col-1 d-flex align-items-center justify-content-center">
      <span style="color: gray;">Влажность</span>
    </div>
  </div>

{% for location_current_weather in forecast.forecast.values %}
    <div class="row">
    <div class="col-2 d-flex align-items-center justify-content-center">
        {{ location_current_weather.current_date }} {{ location_current_weather.current_time }}
    </div>
    <div class="col-1 d-flex align-items-center justify-content-center">
      <b>{{ location_current_weather.temp_min }}&deg;...{{ location_current_weather.temp_max }}&deg;</b>
    </div>
    <div class="col-1 d-flex align-items-center justify-content-center">
      <b>{{ location_current_weather.feels_like }}&deg;</b>
    </div>
    <div class="col-1 d-flex align-items-center justify-content-center">
        <img src="{% static 'weather/images/custom_icon/'|add:location_current_weather.icon|add:'.png' %}" alt="icon" width="40" height="40" title="{{ location_current_weather.weather_desc }}">
    </div>
    <div class="col-2 d-flex align-items-center justify-content-center">
        {{ location_current_weather.weather_desc }}
    </div>
    <div class="col-1 d-flex align-items-center justify-content-center">
        {{ location_current_weather.pressure }}
    </div>
    <div class="col-1 d-flex align-items-center justify-content-center">
        {{ location_current_weather.humidity }}
    </div>
  </div>
{% endfor %}
</div>


{% else %}

<h2 class="h3 mb-3 fw-normal" style="text-align: center;">Чтобы просматривать погоду надо <a href="{% url 'users:login' %}">авторизоваться</a></h2>

{% endif %}

{% endblock %}

siteweather/weather/templates/weather/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1 class="h1 mb-3 fw-normal" style="text-align: center;">{{ title }}</h1>

{% if user.is_authenticated %}

<div class="d-flex align-content-start flex-wrap">

{% for location_id, location_current_weather in locations.items %}

  <div class="card" style="width: 18rem; margin-right: 20px; margin-bottom: 20px; min-width: 400px;">
    <div class="card-header">
      <b>{{ location_current_weather.city.name }},
      {{ location_current_weather.city.country }}, {{ location_current_weather.city.country_name }}</b>
      <img src="{% static 'weather/images/icon/'|add:location_current_weather.icon|add:'.png' %}" alt="icon" width="100" height="100" style="position: absolute; top: 0; right: 0;" title="{{ location_current_weather.weather_desc }}">
      <p style="margin-bottom: 0;">Погода: {{ location_current_weather.weather_desc }}</p>
      <p style="margin-bottom: 0;">Температура: <span style="font-weight: bold;">{{ location_current_weather.temp }} &#8451;</span></p>
      <p style="margin-bottom: 0;">Ощущается как: <span style="font-weight: bold;">{{ location_current_weather.feels_like }} &#8451;</span></p>
      <p style="margin-bottom: 0;">{{ location_current_weather.current_date }}
      {{ location_current_weather.current_time }}
      </p>
    </div>

    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <div class="row">
          <div class="col-6">
            <img src="{% static 'weather/images/cold.png' %}" alt="cold" width="20" height="20" class="d-inline-block align-text-top">
            min {{ location_current_weather.temp_min }} &#8451;
          </div>
          <div class="col-6">
            <img src="{% static 'weather/images/hot.png' %}" alt="hot" width="20" height="20" class="d-inline-block align-text-top">
            max {{ location_current_weather.temp_max }} &#8451;
          </div>
        </div>
      </li>
      <li class="list-group-item">
        <div class="row">
          <div class="col-6">
            <img src="{% static 'weather/images/pressure.png' %}" alt="pressure" width="20" height="20" class="d-inline-block align-text-top">
            Давление {{ location_current_weather.pressure }} мм
          </div>
          <div class="col-6">
            <img src="{% static 'weather/images/humidity.png' %}" alt="humidity" width="20" height="20" class="d-inline-block align-text-top">
            Влажность {{ location_current_weather.humidity }} %
          </div>
        </div>
      </li>
      <li class="list-group-item">
        <div class="row">
          <div class="col-6">
            <img src="{% static 'weather/images/sunrise.png' %}" alt="sunrise" width="20" height="20" class="d-inline-block align-text-top">
            Восход {{ location_current_weather.sunrise }}
          </div>
          <div class="col-6">
            <img src="{% static 'weather/images/sunset.png' %}" alt="sunset" width="20" height="20" class="d-inline-block align-text-top">
            Закат {{ location_current_weather.sunset }}
          </div>
        </div>
      </li>

      <li class="list-group-item">
        <div class="row">
          <div class="col-9">
            <form action="{% url 'forecast' location_id=location_id %}" enctype="application/x-www-form-urlencoded" method="post">
              {% csrf_token %}
              <input type="hidden" name="location_id" value="{{ location_id }}">
              <button name="forecast" class="btn btn-outline-success w-100 py-2">Посмотреть прогноз погоды</button>
            </form>
          </div>
          <div class="col-3">
            <form action="{% url 'home' %}" enctype="application/x-www-form-urlencoded" method="post">
              {% csrf_token %}
              <input type="hidden" name="location_id" value="{{ location_id }}">
              <button name="delete" class="btn btn-outline-danger w-100 py-2">del</button>
            </form>
          </div>
      </li>
    </ul>
  </div>

{% endfor %}

</div>

{% else %}

<h2 class="h3 mb-3 fw-normal" style="text-align: center;">Чтобы просматривать погоду надо <a href="{% url 'users:login' %}">авторизоваться</a></h2>

{% endif %}

{% endblock %}

siteweather/weather/templates/weather/save_error.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>
<h2>{{ error_message }}</h2>

<div class="card" style="width: 18rem; margin-right: 20px; margin-bottom: 20px;">
  <div class="card-header">
    {{ name }}
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Широта: {{ latitude }}</li>
    <li class="list-group-item">Долгота: {{ longitude }}</li>
    <li class="list-group-item">Страна: {{ country }}, {{ country_name }}</li>
  </ul>
</div>

{% endblock %}

siteweather/weather/templates/weather/search.html
{% extends 'base.html' %}

{% block content %}

<h1>{{ title }}</h1>

{% if city_name %}

  <h2>Поиск погоды в городе - “{{ city_name }}”</h2>

  <div class="d-flex align-content-start flex-wrap">
  {% if not error_result %}

    {% for result in search_result %}

      <div class="card" style="width: 18rem; margin-right: 20px; margin-bottom: 20px;">
        <form method="post" action="{% url 'home' %}" enctype="application/x-www-form-urlencoded">
        {% csrf_token %}
        <div class="card-header">
          {{ result.name }}
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">Широта: {{ result.latitude }}</li>
          <li class="list-group-item">Долгота: {{ result.longitude }}</li>
          <li class="list-group-item">Страна: {{ result.country }}, {{ result.country_name }}</li>

          <input type="hidden" name="name" value="{{ result.name }}">
          <input type="hidden" name="latitude" value="{{ result.latitude }}">
          <input type="hidden" name="longitude" value="{{ result.longitude }}">
          <input type="hidden" name="country" value="{{ result.country }}">

          <li class="list-group-item"><button name="save" class="btn btn-outline-success w-100 py-2">Добавить</button></li>
        </ul>
        </form>
      </div>

    {% endfor %}

    </div>
    {% else %}
    <h2>{{ error_result.message }}</h2>
    {% endif %}

{% else %}

<h2>Введен пустой запрос в поле поиска, попробуйте заново</h2>

{% endif %}

{% endblock %}